apiVersion: apps/v1
kind: deployment
metadata:
  name: docker-k8s-demo
  labels:
    app: docker-k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-k8s-demo
  template:
    metadata:
      labels:
        app: docker-k8s-demo
    spec:
      containers:
        - name: docker-k8s-demo
          image: srikantsingh51/demo
          ports:
          - containerPort: 8080