apiVersion: v1
kind: Service
metadata:
  name: docker-k8s-demo
  labels:
    name: docker-k8s-demo
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: docker-k8s-demo
  type: LoadBalancer